### ISSUE TITLE
Request: Skip by Reg-Ex

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Donny87/autosub-bootstrapbill#119]
```
I'd like to see a possibility to skip files by Regular Expression.

Situation: 
I Download all my TV Series, let Autosub get the subtitles for me, then use 
MKVmerge to merge the subtitles in the MKV. All of the merged files have a 
common expression in them (Example: seriename.s01e01.720p.merged-subs.ext). I 
merge the files because my TV will not show external subtitles over DLNA, but 
will show them merged. But now Auto-Sub keeps downloading a new srt for the 
already merged MKV. 

Easiest way of going around this problem would be for me to able to set a 
regular expression in the settings to skip downloading subtitles if a file has 
this expression in it.


```

Original issue reported on code.google.com by `kevenlef...@gmail.com` on 24 Jul 2014 at 11:38

**Comment by BenjV** [comment]
You can use my postprocessing script to move the files to another location, so autosub won't see them anymore.
My posprocessscript is also able to merge the sub into the .mkv file.
It does it with ffmpeg, so that should be installed on the system.
Please read the comments in the script for more details.
If you have questions just ask.
Here you can download the script. It is written in python just like autosub.
https://www.dropbox.com/s/02pps94ahfhaf3r/AutoSubPostProcess.py?dl=0
